[package]
name = "opentelemetry_api"
version = "0.1.0"
authors = ["Greg Bowyer <gbowyer@fastmail.co.uk>"]
description = "The Opentelemetry API expressed in Rust"
license = "Apache-2.0"
edition = "2018"

[dependencies]
rand = "0.6.5"
bitflags = "1.1.0"

[dev-dependencies]
proptest = "0.9.4"
